import MathProject.Basic
import MathProject.OntologicalMachine
import MathProject.OntologicalFriction
import MathProject.CategoricalMachine
import MathProject.AdversarialTrap
import MathProject.CategoricalColimits
import MathProject.MatroidFriction
import MathProject.SubmodularFriction
