import MathProject.Basic
import MathProject.CategoricalColimits
import MathProject.BasisDiscovery
import MathProject.Friction
import MathProject.CategoricalMachine
import MathProject.LoewyLength
import MathProject.ThinCategoryLattice
import MathProject.A3ManifoldStrain
import MathProject.TorFrictionStrain
import MathProject.TravelFunctor

#print axioms BasisDiscovery.novelty_of_fixedPriorityPhi
#print axioms CategoricalMachine.loewy_length_exists
#print axioms CategoricalMachine.reconstruction
#print axioms CategoricalMachine.categorical_friction_bound
#print axioms rank_collapse
#print axioms ThinCategoryLattice.thin_mono
#print axioms ThinCategoryLattice.subobject_mono
#print axioms ThinCategoryLattice.thin_extension_splits
#print axioms ThinCategoryLattice.tamari4_card
#print axioms ThinCategoryLattice.rootA3_facetK5_equiv
#print axioms ThinCategoryLattice.a3_facet_count
#print axioms A3ManifoldStrain.cartanForm_pos_def
#print axioms A3ManifoldStrain.coupled_strain_alpha12
#print axioms TorFrictionStrain.defect_nonneg
#print axioms TorFrictionStrain.modular_defect_zero
#print axioms TravelFunctor.TravelExperience.comp_assoc
#print axioms TravelFunctor.action_strictly_increases
#print axioms FunctorialGeometry.loewy_length_exists
#print axioms FunctorialGeometry.loewy_residual_colimit_vanishes
#print axioms FunctorialGeometry.facetKn2_diagonal_equiv
#print axioms FunctorialGeometry.rootAn_diagonal_equiv
#print axioms FunctorialGeometry.rootA3_facetK5_equiv
#print axioms FunctorialGeometry.isAlmostPositiveRootA3_iff
#print axioms FunctorialGeometry.rootA3_cartan_norm
#print axioms FunctorialGeometry.rootA3_cyclic_length_pentagon
#print axioms FunctorialGeometry.rootA3_cyclic_length_square
#print axioms FunctorialGeometry.cartanEnergy_pos_def
#print axioms FunctorialGeometry.cellular_shortExact
#print axioms FunctorialGeometry.rootAn_pos_crosses_fan_iff
#print axioms FunctorialGeometry.compatible_with_fan_iff_neg_simple
#print axioms FunctorialGeometry.cartanEnergy_eq_cartanMatrix
#print axioms FunctorialGeometry.cartanEnergy_three
#print axioms FunctorialGeometry.rootAn_cartan_norm
#print axioms FunctorialGeometry.rootAn_to_vec_injective
#print axioms FunctorialGeometry.cyclic_length_count
